export const homeObjOne = {
    primary:true, 
    lightBg: false,    
    imgStart: true, 
    lightTopLine: true,
    lightTextDesc:true, 
    buttonLabel: 'Get Started', 
    description: 'We help you to get your essential medicinal requirments to your doorstep!', 
    headline: 'Find the Best Pharmacy for You. We Have Many.',
    lightText:true,
    topLine:'YOUR HEALTH - OUR WEALTH',
    img: require('./img/pic.svg').default, 
    alt:'we deliver you the best!',
    start: true,
};

export const homeObjTwo = {
    primary:false, 
    lightBg: true,
    imgStart: false, 
    lightTopLine: false,
    lightTextDesc:false, 
    buttonLabel: 'Get Started', 
    description: 'We help you to get your customers', 
    headline: 'Let Your Customers Reach You From Home.',
    lightText:false,
    topLine:'YOUR HEALTH - OUR WEALTH',
    img:require('./img/pic3.svg').default,
    alt:'This is easy!',
    start: false,
};